# https://towardsdatascience.com/managing-project-specific-environments-with-conda-406365a539ab

# conda env create -f environment.yml

name: HTS

channels:
    - defaults
    - bioconda

dependencies:
    - fastqc=0.11.9



